### ISSUE TITLE
Instalación servidor

### ISSUE THREAD

**Issue by Isiirribarra** [IIC2413/Syllabus-2023-1#32]
Hola,he estado intentando instalar el servidor en mi mac pero no he podido. 
Los pasos que realizo son finder-> ir-> conectarse a servidor... -> ingreso: smb://codd.ing.puc.cl -> y me tira que hubo un problema para conectarse al servidor

![Captura de Pantalla 2023-03-30 a la(s) 11 58 52](https://user-images.githubusercontent.com/103218010/228879005-40d00719-44e6-4bfb-8010-81cd2b5c173b.png)

**Comment by Paldana99** [comment]
Probaste directamente en terminal con comando ssh? O Puede utilizar una interfaz gráfica como filezilla.

En la [Ayudantia Servidor](https://github.com/IIC2413/Syllabus-2023-1/blob/main/Ayudantias/Ayudania%202/ay1-servidor.pdf) esta en detalle los pasos a seguir utilizando esos métodos.

**Comment by Isiirribarra** [comment]
al final lo pude resolver, gracias
