### ISSUE TITLE
Importar CSV

### ISSUE THREAD

**Issue by ymotomy** [IIC2413/Syllabus-2023-1#35]
Hola, tengo un problema al copiar los datos de un csv a una relacion. 
Al ocupar el comando `\COPY users (columna_names) FROM ‘relative/path/to/file.csv’
DELIMITER ‘,’ CSV HEADER;`, pongo la ruta absoluta pero dice que el directorio no ha sido encontrado `No such file or directory`. Como puedo solucionar esto?
PD. Como no se desde que directorio estoy trabajndo no puedo poner la ruta relativa

**Comment by paulmacguire** [comment]
Hola! Lo que te recomiendo hacer es lo siguiente:![image](https://user-images.githubusercontent.com/101202383/229268384-c2e12f63-e1ee-43a7-a41e-c6ab22c5a898.jpeg)

Haz click en donde está la flecha (estando en la carpeta en donde está tu CSV) y borra todo lo que esté dentro, y escribe "cmd" (sin las comillas). Esto hará que se abra la terminal en ese directorio, y luego como ruta relativa simplemente pon el nombre de tu archivo CSV y ahí te debería funcionar. Saludos!

**Comment by ymotomy** [comment]
![Captura de pantalla 2023-04-01 114317](https://user-images.githubusercontent.com/96211700/229296018-40785077-ca04-4be9-970a-f2fad9906658.png)


Lo hice y sigue sin funcionarme):

**Comment by NicolasOlmosQuiroga** [comment]
Hola!, el comando deberia ser este:

\COPY tiendas (calle, numero, comuna, region, fono) FROM 'tiendas.csv' DELIMITER ',' CSV HEADER;

Como muchas otras cosas de Postgres, el archivo de tiendas.csv debe estar en comillas simples para que funcione.

Saludos,

**Comment by AlonsoPizarr** [comment]
Hola,
Yo tambien tengo el mismo problema, abro cmd desde la carpeta donde esta mi archivo csv, pero aun asi me da el mismo error
![copy2](https://user-images.githubusercontent.com/110861608/229929918-3f5d063d-2185-4683-ae21-f337ae492f74.png)

**Comment by ymotomy** [comment]
Hoy en clases le pregunte a un ayudante y pude hacerlo:
El archivo hay que subirlo al servidor mediante filezilla, el ayudante me recomendo crear una carpeta CSV y ahi guardar todos estos archivos.
Cuando ingresemos al servidor mediante el terminal, con el comando ssh grupoXX@codd.ing.puc.cl, estaremos trabajando en el so del servidor, que es linux, por lo tanto hay que utilizar los comandos de aqui. Para veificar que la carpeta y/o los archivos se han subido correctamente utilizaremos el comando `ls` y tendrian que aparecer, aqui ya estarian listos para poder cargarlos.
Luego de ingresar `psql` en el terminal, ya podremos escribir el comando
`\COPY relacion (atributos) FROM 'CSV/archivo.csv' DELIMITER ',' CSV HEADER;`
y se habra cargado la informacion del archivo

**Comment by AlonsoPizarr** [comment]
Ahí por fin me funcionó
muchas gracias!
