### ISSUE TITLE
Duda; grupo par

### ISSUE THREAD

**Issue by Isiirribarra** [IIC2413/Syllabus-2023-1#37]
Hola, cuando se refiere en "Compras: cada compra puede contener varios productos". Se refiere a que una compra puede tener una lista de id de productos? Ejemplo la 

> compra 1 tiene los id de productos (1,2,3)? 

O se refiere a que la 

> compra 1  id  producto 1 

>  compra 1 id producto 2,

>  ... 

No se si se entiende. Al final es como uno lo registra en la tabla. Si separados o juntos.

**Comment by Paldana99** [comment]
Exactamente, es una diferencia de como se registra en la tabla. Pero cada una tiene ventajas sobre las otras. Para esto recomiendo pensar en como serian las consultas en algebra relacional/sql y veran que hay una que saldrá mas fácil que en otra.

**Comment by Isiirribarra** [comment]
Gracias
